// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datagathering.proxies;

public class DataEntry
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataEntryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataGathering.DataEntry";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		DateOfBirth("DateOfBirth"),
		MaritalStatus("MaritalStatus"),
		SocialSecurityNumber("SocialSecurityNumber"),
		StreetAddress("StreetAddress"),
		City("City"),
		State("State"),
		ZipCode("ZipCode"),
		Phone("Phone"),
		Email("Email"),
		EmergencyContactFirstName("EmergencyContactFirstName"),
		EmergencyContactLastName("EmergencyContactLastName"),
		EmergencyContactNumber("EmergencyContactNumber"),
		EmergencyContactEmail("EmergencyContactEmail"),
		EmergencyContactRelationship("EmergencyContactRelationship"),
		RefereeFirstName("RefereeFirstName"),
		RefereeLastName("RefereeLastName"),
		RefereeJobTitle("RefereeJobTitle"),
		RefereeCompany("RefereeCompany"),
		RefereeEmail("RefereeEmail"),
		RefereePhone("RefereePhone"),
		BankName("BankName"),
		BankAccountNumber("BankAccountNumber"),
		ABANumber("ABANumber"),
		ProfileImage("DataGathering.ProfileImage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataEntry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataGathering.DataEntry"));
	}

	protected DataEntry(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataEntryMendixObject)
	{
		if (dataEntryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DataGathering.DataEntry", dataEntryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataGathering.DataEntry");

		this.dataEntryMendixObject = dataEntryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DataEntry.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datagathering.proxies.DataEntry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datagathering.proxies.DataEntry.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datagathering.proxies.DataEntry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datagathering.proxies.DataEntry(context, mendixObject);
	}

	public static datagathering.proxies.DataEntry load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datagathering.proxies.DataEntry.initialize(context, mendixObject);
	}

	public static java.util.List<datagathering.proxies.DataEntry> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datagathering.proxies.DataEntry> result = new java.util.ArrayList<datagathering.proxies.DataEntry>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataGathering.DataEntry" + xpathConstraint))
			result.add(datagathering.proxies.DataEntry.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * Set value of MaritalStatus
	 * @param maritalstatus
	 */
	public final datagathering.proxies.MaritalStatus getMaritalStatus()
	{
		return getMaritalStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MaritalStatus
	 */
	public final datagathering.proxies.MaritalStatus getMaritalStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MaritalStatus.toString());
		if (obj == null)
			return null;

		return datagathering.proxies.MaritalStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MaritalStatus
	 * @param maritalstatus
	 */
	public final void setMaritalStatus(datagathering.proxies.MaritalStatus maritalstatus)
	{
		setMaritalStatus(getContext(), maritalstatus);
	}

	/**
	 * Set value of MaritalStatus
	 * @param context
	 * @param maritalstatus
	 */
	public final void setMaritalStatus(com.mendix.systemwideinterfaces.core.IContext context, datagathering.proxies.MaritalStatus maritalstatus)
	{
		if (maritalstatus != null)
			getMendixObject().setValue(context, MemberNames.MaritalStatus.toString(), maritalstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.MaritalStatus.toString(), null);
	}

	/**
	 * @return value of SocialSecurityNumber
	 */
	public final java.lang.String getSocialSecurityNumber()
	{
		return getSocialSecurityNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of SocialSecurityNumber
	 */
	public final java.lang.String getSocialSecurityNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SocialSecurityNumber.toString());
	}

	/**
	 * Set value of SocialSecurityNumber
	 * @param socialsecuritynumber
	 */
	public final void setSocialSecurityNumber(java.lang.String socialsecuritynumber)
	{
		setSocialSecurityNumber(getContext(), socialsecuritynumber);
	}

	/**
	 * Set value of SocialSecurityNumber
	 * @param context
	 * @param socialsecuritynumber
	 */
	public final void setSocialSecurityNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String socialsecuritynumber)
	{
		getMendixObject().setValue(context, MemberNames.SocialSecurityNumber.toString(), socialsecuritynumber);
	}

	/**
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress()
	{
		return getStreetAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StreetAddress.toString());
	}

	/**
	 * Set value of StreetAddress
	 * @param streetaddress
	 */
	public final void setStreetAddress(java.lang.String streetaddress)
	{
		setStreetAddress(getContext(), streetaddress);
	}

	/**
	 * Set value of StreetAddress
	 * @param context
	 * @param streetaddress
	 */
	public final void setStreetAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String streetaddress)
	{
		getMendixObject().setValue(context, MemberNames.StreetAddress.toString(), streetaddress);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of ZipCode
	 */
	public final java.lang.String getZipCode()
	{
		return getZipCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ZipCode
	 */
	public final java.lang.String getZipCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZipCode.toString());
	}

	/**
	 * Set value of ZipCode
	 * @param zipcode
	 */
	public final void setZipCode(java.lang.String zipcode)
	{
		setZipCode(getContext(), zipcode);
	}

	/**
	 * Set value of ZipCode
	 * @param context
	 * @param zipcode
	 */
	public final void setZipCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zipcode)
	{
		getMendixObject().setValue(context, MemberNames.ZipCode.toString(), zipcode);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of EmergencyContactFirstName
	 */
	public final java.lang.String getEmergencyContactFirstName()
	{
		return getEmergencyContactFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmergencyContactFirstName
	 */
	public final java.lang.String getEmergencyContactFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmergencyContactFirstName.toString());
	}

	/**
	 * Set value of EmergencyContactFirstName
	 * @param emergencycontactfirstname
	 */
	public final void setEmergencyContactFirstName(java.lang.String emergencycontactfirstname)
	{
		setEmergencyContactFirstName(getContext(), emergencycontactfirstname);
	}

	/**
	 * Set value of EmergencyContactFirstName
	 * @param context
	 * @param emergencycontactfirstname
	 */
	public final void setEmergencyContactFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emergencycontactfirstname)
	{
		getMendixObject().setValue(context, MemberNames.EmergencyContactFirstName.toString(), emergencycontactfirstname);
	}

	/**
	 * @return value of EmergencyContactLastName
	 */
	public final java.lang.String getEmergencyContactLastName()
	{
		return getEmergencyContactLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmergencyContactLastName
	 */
	public final java.lang.String getEmergencyContactLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmergencyContactLastName.toString());
	}

	/**
	 * Set value of EmergencyContactLastName
	 * @param emergencycontactlastname
	 */
	public final void setEmergencyContactLastName(java.lang.String emergencycontactlastname)
	{
		setEmergencyContactLastName(getContext(), emergencycontactlastname);
	}

	/**
	 * Set value of EmergencyContactLastName
	 * @param context
	 * @param emergencycontactlastname
	 */
	public final void setEmergencyContactLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emergencycontactlastname)
	{
		getMendixObject().setValue(context, MemberNames.EmergencyContactLastName.toString(), emergencycontactlastname);
	}

	/**
	 * @return value of EmergencyContactNumber
	 */
	public final java.lang.String getEmergencyContactNumber()
	{
		return getEmergencyContactNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EmergencyContactNumber
	 */
	public final java.lang.String getEmergencyContactNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmergencyContactNumber.toString());
	}

	/**
	 * Set value of EmergencyContactNumber
	 * @param emergencycontactnumber
	 */
	public final void setEmergencyContactNumber(java.lang.String emergencycontactnumber)
	{
		setEmergencyContactNumber(getContext(), emergencycontactnumber);
	}

	/**
	 * Set value of EmergencyContactNumber
	 * @param context
	 * @param emergencycontactnumber
	 */
	public final void setEmergencyContactNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emergencycontactnumber)
	{
		getMendixObject().setValue(context, MemberNames.EmergencyContactNumber.toString(), emergencycontactnumber);
	}

	/**
	 * @return value of EmergencyContactEmail
	 */
	public final java.lang.String getEmergencyContactEmail()
	{
		return getEmergencyContactEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of EmergencyContactEmail
	 */
	public final java.lang.String getEmergencyContactEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmergencyContactEmail.toString());
	}

	/**
	 * Set value of EmergencyContactEmail
	 * @param emergencycontactemail
	 */
	public final void setEmergencyContactEmail(java.lang.String emergencycontactemail)
	{
		setEmergencyContactEmail(getContext(), emergencycontactemail);
	}

	/**
	 * Set value of EmergencyContactEmail
	 * @param context
	 * @param emergencycontactemail
	 */
	public final void setEmergencyContactEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emergencycontactemail)
	{
		getMendixObject().setValue(context, MemberNames.EmergencyContactEmail.toString(), emergencycontactemail);
	}

	/**
	 * Set value of EmergencyContactRelationship
	 * @param emergencycontactrelationship
	 */
	public final datagathering.proxies.EmergencyContactRelationship getEmergencyContactRelationship()
	{
		return getEmergencyContactRelationship(getContext());
	}

	/**
	 * @param context
	 * @return value of EmergencyContactRelationship
	 */
	public final datagathering.proxies.EmergencyContactRelationship getEmergencyContactRelationship(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EmergencyContactRelationship.toString());
		if (obj == null)
			return null;

		return datagathering.proxies.EmergencyContactRelationship.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EmergencyContactRelationship
	 * @param emergencycontactrelationship
	 */
	public final void setEmergencyContactRelationship(datagathering.proxies.EmergencyContactRelationship emergencycontactrelationship)
	{
		setEmergencyContactRelationship(getContext(), emergencycontactrelationship);
	}

	/**
	 * Set value of EmergencyContactRelationship
	 * @param context
	 * @param emergencycontactrelationship
	 */
	public final void setEmergencyContactRelationship(com.mendix.systemwideinterfaces.core.IContext context, datagathering.proxies.EmergencyContactRelationship emergencycontactrelationship)
	{
		if (emergencycontactrelationship != null)
			getMendixObject().setValue(context, MemberNames.EmergencyContactRelationship.toString(), emergencycontactrelationship.toString());
		else
			getMendixObject().setValue(context, MemberNames.EmergencyContactRelationship.toString(), null);
	}

	/**
	 * @return value of RefereeFirstName
	 */
	public final java.lang.String getRefereeFirstName()
	{
		return getRefereeFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereeFirstName
	 */
	public final java.lang.String getRefereeFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereeFirstName.toString());
	}

	/**
	 * Set value of RefereeFirstName
	 * @param refereefirstname
	 */
	public final void setRefereeFirstName(java.lang.String refereefirstname)
	{
		setRefereeFirstName(getContext(), refereefirstname);
	}

	/**
	 * Set value of RefereeFirstName
	 * @param context
	 * @param refereefirstname
	 */
	public final void setRefereeFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereefirstname)
	{
		getMendixObject().setValue(context, MemberNames.RefereeFirstName.toString(), refereefirstname);
	}

	/**
	 * @return value of RefereeLastName
	 */
	public final java.lang.String getRefereeLastName()
	{
		return getRefereeLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereeLastName
	 */
	public final java.lang.String getRefereeLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereeLastName.toString());
	}

	/**
	 * Set value of RefereeLastName
	 * @param refereelastname
	 */
	public final void setRefereeLastName(java.lang.String refereelastname)
	{
		setRefereeLastName(getContext(), refereelastname);
	}

	/**
	 * Set value of RefereeLastName
	 * @param context
	 * @param refereelastname
	 */
	public final void setRefereeLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereelastname)
	{
		getMendixObject().setValue(context, MemberNames.RefereeLastName.toString(), refereelastname);
	}

	/**
	 * @return value of RefereeJobTitle
	 */
	public final java.lang.String getRefereeJobTitle()
	{
		return getRefereeJobTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereeJobTitle
	 */
	public final java.lang.String getRefereeJobTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereeJobTitle.toString());
	}

	/**
	 * Set value of RefereeJobTitle
	 * @param refereejobtitle
	 */
	public final void setRefereeJobTitle(java.lang.String refereejobtitle)
	{
		setRefereeJobTitle(getContext(), refereejobtitle);
	}

	/**
	 * Set value of RefereeJobTitle
	 * @param context
	 * @param refereejobtitle
	 */
	public final void setRefereeJobTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereejobtitle)
	{
		getMendixObject().setValue(context, MemberNames.RefereeJobTitle.toString(), refereejobtitle);
	}

	/**
	 * @return value of RefereeCompany
	 */
	public final java.lang.String getRefereeCompany()
	{
		return getRefereeCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereeCompany
	 */
	public final java.lang.String getRefereeCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereeCompany.toString());
	}

	/**
	 * Set value of RefereeCompany
	 * @param refereecompany
	 */
	public final void setRefereeCompany(java.lang.String refereecompany)
	{
		setRefereeCompany(getContext(), refereecompany);
	}

	/**
	 * Set value of RefereeCompany
	 * @param context
	 * @param refereecompany
	 */
	public final void setRefereeCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereecompany)
	{
		getMendixObject().setValue(context, MemberNames.RefereeCompany.toString(), refereecompany);
	}

	/**
	 * @return value of RefereeEmail
	 */
	public final java.lang.String getRefereeEmail()
	{
		return getRefereeEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereeEmail
	 */
	public final java.lang.String getRefereeEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereeEmail.toString());
	}

	/**
	 * Set value of RefereeEmail
	 * @param refereeemail
	 */
	public final void setRefereeEmail(java.lang.String refereeemail)
	{
		setRefereeEmail(getContext(), refereeemail);
	}

	/**
	 * Set value of RefereeEmail
	 * @param context
	 * @param refereeemail
	 */
	public final void setRefereeEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereeemail)
	{
		getMendixObject().setValue(context, MemberNames.RefereeEmail.toString(), refereeemail);
	}

	/**
	 * @return value of RefereePhone
	 */
	public final java.lang.String getRefereePhone()
	{
		return getRefereePhone(getContext());
	}

	/**
	 * @param context
	 * @return value of RefereePhone
	 */
	public final java.lang.String getRefereePhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefereePhone.toString());
	}

	/**
	 * Set value of RefereePhone
	 * @param refereephone
	 */
	public final void setRefereePhone(java.lang.String refereephone)
	{
		setRefereePhone(getContext(), refereephone);
	}

	/**
	 * Set value of RefereePhone
	 * @param context
	 * @param refereephone
	 */
	public final void setRefereePhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refereephone)
	{
		getMendixObject().setValue(context, MemberNames.RefereePhone.toString(), refereephone);
	}

	/**
	 * @return value of BankName
	 */
	public final java.lang.String getBankName()
	{
		return getBankName(getContext());
	}

	/**
	 * @param context
	 * @return value of BankName
	 */
	public final java.lang.String getBankName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BankName.toString());
	}

	/**
	 * Set value of BankName
	 * @param bankname
	 */
	public final void setBankName(java.lang.String bankname)
	{
		setBankName(getContext(), bankname);
	}

	/**
	 * Set value of BankName
	 * @param context
	 * @param bankname
	 */
	public final void setBankName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankname)
	{
		getMendixObject().setValue(context, MemberNames.BankName.toString(), bankname);
	}

	/**
	 * @return value of BankAccountNumber
	 */
	public final java.lang.String getBankAccountNumber()
	{
		return getBankAccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccountNumber
	 */
	public final java.lang.String getBankAccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BankAccountNumber.toString());
	}

	/**
	 * Set value of BankAccountNumber
	 * @param bankaccountnumber
	 */
	public final void setBankAccountNumber(java.lang.String bankaccountnumber)
	{
		setBankAccountNumber(getContext(), bankaccountnumber);
	}

	/**
	 * Set value of BankAccountNumber
	 * @param context
	 * @param bankaccountnumber
	 */
	public final void setBankAccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankaccountnumber)
	{
		getMendixObject().setValue(context, MemberNames.BankAccountNumber.toString(), bankaccountnumber);
	}

	/**
	 * @return value of ABANumber
	 */
	public final java.lang.String getABANumber()
	{
		return getABANumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ABANumber
	 */
	public final java.lang.String getABANumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ABANumber.toString());
	}

	/**
	 * Set value of ABANumber
	 * @param abanumber
	 */
	public final void setABANumber(java.lang.String abanumber)
	{
		setABANumber(getContext(), abanumber);
	}

	/**
	 * Set value of ABANumber
	 * @param context
	 * @param abanumber
	 */
	public final void setABANumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String abanumber)
	{
		getMendixObject().setValue(context, MemberNames.ABANumber.toString(), abanumber);
	}

	/**
	 * @return value of ProfileImage
	 */
	public final datagathering.proxies.Profile getProfileImage() throws com.mendix.core.CoreException
	{
		return getProfileImage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfileImage
	 */
	public final datagathering.proxies.Profile getProfileImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datagathering.proxies.Profile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProfileImage.toString());
		if (identifier != null)
			result = datagathering.proxies.Profile.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProfileImage
	 * @param profileimage
	 */
	public final void setProfileImage(datagathering.proxies.Profile profileimage)
	{
		setProfileImage(getContext(), profileimage);
	}

	/**
	 * Set value of ProfileImage
	 * @param context
	 * @param profileimage
	 */
	public final void setProfileImage(com.mendix.systemwideinterfaces.core.IContext context, datagathering.proxies.Profile profileimage)
	{
		if (profileimage == null)
			getMendixObject().setValue(context, MemberNames.ProfileImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProfileImage.toString(), profileimage.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataEntryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datagathering.proxies.DataEntry that = (datagathering.proxies.DataEntry) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataGathering.DataEntry";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
