// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datagathering.proxies;

public class Document extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataGathering.Document";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SupportingDocuments("DataGathering.SupportingDocuments");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Document(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataGathering.Document"));
	}

	protected Document(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentMendixObject)
	{
		super(context, documentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DataGathering.Document", documentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataGathering.Document");
	}

	/**
	 * @deprecated Use 'Document.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datagathering.proxies.Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datagathering.proxies.Document.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datagathering.proxies.Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datagathering.proxies.Document(context, mendixObject);
	}

	public static datagathering.proxies.Document load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datagathering.proxies.Document.initialize(context, mendixObject);
	}

	public static java.util.List<datagathering.proxies.Document> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datagathering.proxies.Document> result = new java.util.ArrayList<datagathering.proxies.Document>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataGathering.Document" + xpathConstraint))
			result.add(datagathering.proxies.Document.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of SupportingDocuments
	 */
	public final datagathering.proxies.DataEntry getSupportingDocuments() throws com.mendix.core.CoreException
	{
		return getSupportingDocuments(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportingDocuments
	 */
	public final datagathering.proxies.DataEntry getSupportingDocuments(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datagathering.proxies.DataEntry result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SupportingDocuments.toString());
		if (identifier != null)
			result = datagathering.proxies.DataEntry.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SupportingDocuments
	 * @param supportingdocuments
	 */
	public final void setSupportingDocuments(datagathering.proxies.DataEntry supportingdocuments)
	{
		setSupportingDocuments(getContext(), supportingdocuments);
	}

	/**
	 * Set value of SupportingDocuments
	 * @param context
	 * @param supportingdocuments
	 */
	public final void setSupportingDocuments(com.mendix.systemwideinterfaces.core.IContext context, datagathering.proxies.DataEntry supportingdocuments)
	{
		if (supportingdocuments == null)
			getMendixObject().setValue(context, MemberNames.SupportingDocuments.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SupportingDocuments.toString(), supportingdocuments.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datagathering.proxies.Document that = (datagathering.proxies.Document) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataGathering.Document";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
