// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datagathering.proxies;

public class Profile extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataGathering.Profile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ProfileImage("DataGathering.ProfileImage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Profile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataGathering.Profile"));
	}

	protected Profile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profileMendixObject)
	{
		super(context, profileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DataGathering.Profile", profileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataGathering.Profile");
	}

	/**
	 * @deprecated Use 'Profile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datagathering.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datagathering.proxies.Profile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datagathering.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datagathering.proxies.Profile(context, mendixObject);
	}

	public static datagathering.proxies.Profile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datagathering.proxies.Profile.initialize(context, mendixObject);
	}

	public static java.util.List<datagathering.proxies.Profile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datagathering.proxies.Profile> result = new java.util.ArrayList<datagathering.proxies.Profile>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataGathering.Profile" + xpathConstraint))
			result.add(datagathering.proxies.Profile.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ProfileImage
	 */
	public final datagathering.proxies.DataEntry getProfileImage() throws com.mendix.core.CoreException
	{
		return getProfileImage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfileImage
	 */
	public final datagathering.proxies.DataEntry getProfileImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datagathering.proxies.DataEntry result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProfileImage.toString());
		if (identifier != null)
			result = datagathering.proxies.DataEntry.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProfileImage
	 * @param profileimage
	 */
	public final void setProfileImage(datagathering.proxies.DataEntry profileimage)
	{
		setProfileImage(getContext(), profileimage);
	}

	/**
	 * Set value of ProfileImage
	 * @param context
	 * @param profileimage
	 */
	public final void setProfileImage(com.mendix.systemwideinterfaces.core.IContext context, datagathering.proxies.DataEntry profileimage)
	{
		if (profileimage == null)
			getMendixObject().setValue(context, MemberNames.ProfileImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProfileImage.toString(), profileimage.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datagathering.proxies.Profile that = (datagathering.proxies.Profile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataGathering.Profile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
